package antgame;

/**
 * Base abstract class for all Ant Game exceptions
 * Constructors generated by Eclipse to encapsulate superclass constructors
 * @author Alex
 *
 */
public abstract class AntGameException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public AntGameException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public AntGameException(String message, Throwable cause,
			boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

	public AntGameException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public AntGameException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public AntGameException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}
	

}
